data:
  base_augmentation:
    resize:
      width: 224
      height: 224
  
  train:
    batch_size: 4
    num_workers: 8

    # augmentation:
    #   resize / crop / hflip / rotate / affine / sharpen contrast
    #   crop:
    #     p: 1
    #     width: 150
    #     height: 150
    #   hflip:
    #     p: 1
    #   rotate:
    #     p: 1
    #     limit: 45
    #   affine: 
    #     p: 1
    #     scale: [0.9, 1.1]
    #     translate_percent: [0.1, 0.1]
    #     rotate: 30
    #     shear: 15
    #   sharpen:
    #     p: 1
    #     alpha: [0.2, 0.5]
    #     lightness: [0.5, 1.5]
    #   contrast:
    #     p: 1
    #     brightness_limit: 0.3
    #     contrast_limit: 0.3

  val:
    batch_size: 4  
    num_workers: 4

  inference:
    batch_size: 2
    num_workers: 4
    # tta:
    #   HorizontalFlip: {}
      # VerticalFlit: {}
      # Rotate90:
      #   angle: [0, 90, 180, 270]  # List[0, 90, 180, 270]
      # Scale:
      #   scales: [1, 1.2, 1.4]         
      #   interpolation: "bilinear"  # "nearest" / "linear"
      # Resize:
      #   sizes: [(512, 512), (1024, 1024)]
      #   original_size: (1024, 1024)
      #   interpolation: "bilinear" # "nearest" / "linear"
      # Add:
      #   values: []
      # Multiply:
      #   factors: []
      # FiveCrops:
      #   crop_height: 512
      #   crop_width: 512

