paths:
  output_dir: "./outputs/"

  train_image_root: "./data/train/DCM"
  train_label_root: "./data/train/outputs_json"

  inference_image_root: "./data/test/DCM"
  inference_label_root: "./data/test/outputs_json"