train:
  batch_size: 4
  num_epochs: 50
  n_splits: 5
  threshold: 0.5
  
   
  metric: "dice_coef"
  # accuracy / f1 / precision / recall / mse / dice_coef
  
  criterion: "CrossEntropyLoss"
  # CrossEntropyLoss / BCE

  optimizer:
    name: "Adam"
    # Adam / SGD
    weight_decay: 0.000001
    momentum: 0.9
    learning_rate: 0.0001

  lr_scheduler:
    name: "ReduceLROnPlateau"
    factor: 0.1
    patience: 3
    min_lr: 1e-6
    monitor: 'metric'

  early_stopping:
    patience: 5
    min_delta: 0.001
    evidence: 'loss'
    monitor: 'metric'

model:
  name: "fcn_50"
  # fcn_50 / 
  pretrained: True
  