train:
  num_epochs: 10
  n_splits: 5
  threshold: 0.5
   
  metric: 
    name: "dice_coef"
  # accuracy / f1 / precision / recall / mse / dice_coef

  criterion: 
    name: "bce+dice"
  # CrossEntropy / bce / bce+dice / dice / StructureLoss(for SAM2-UNET) / focal+dice / unet3p

  optimizer:
    name: "Adam"
    # Adam / SGD / AdamW
    config:
      weight_decay: 1.e-6
      # momentum: 0.9
      lr: 1.e-4

  lr_scheduler:
    name: "ReduceLROnPlateau"
    monitor: "metric"
    config:
      factor: 0.1
      patience: 20
      min_lr: 1.e-6
      verbose: True

  early_stopping:
    patience: 5
    min_delta: 0.001
    evidence: 'loss'
    monitor: 'metric'

model:
  #name: "myUnet"
  name: "smp_unet"

  # fcn_50 /
  config:
    pretrained: True
  