train:
  num_epochs: 10
  n_splits: 5
  threshold: 0.5
   
  metric: 
    name: "dice_coef"
  # accuracy / f1 / precision / recall / mse / dice_coef

  criterion: 
    name: "bce+dice"
  # CrossEntropyLoss / BCEWithLogitsLoss / bce+dice / dice / StructureLoss(for SAM2-UNET)

  optimizer:
    name: "Adam"
    # Adam / SGD
    config:
      weight_decay: 1.e-6
      # momentum: 0.9
      lr: 1.e-4

  lr_scheduler:
    name: "ReduceLROnPlateau"
    monitor: "metric"
    config:
      factor: 0.1
      patience: 20
      min_lr: 1.e-6
      verbose: True

  early_stopping:
    patience: 5
    min_delta: 0.001
    evidence: 'loss'
    monitor: 'metric'

model:
  name: "smp_unet++_resnet34"

  # torchvision : fcn_50 / fcn_101 / deeplabv3_50 / deeplabv3_101 

  # smp : smp_unet / smp_unet++
  # encoder: resnet34 / resnet101 / efficientnet-b[0-7] / tu-maxvit_tiny_tf512 
  # ex : smp_unet++_efficientnet-b5

  # 이외 : myUnet / sam2unet_[tiny,base,large]

  config:
    pretrained: True
  