classes:
- finger-1
- finger-2
- finger-3
- finger-4
- finger-5
- finger-6
- finger-7
- finger-8
- finger-9
- finger-10
- finger-11
- finger-12
- finger-13
- finger-14
- finger-15
- finger-16
- finger-17
- finger-18
- finger-19
- Trapezium
- Trapezoid
- Capitate
- Hamate
- Scaphoid
- Lunate
- Triquetrum
- Pisiform
- Radius
- Ulna
data:
  inference:
    batch_size: 2
    num_workers: 4
  train:
    batch_size: 4
    num_workers: 8
  val:
    batch_size: 4
    num_workers: 0
    val_step: 5
developer: hg
device: cuda
mode: train
model:
  config:
    pretrained: true
  name: fcn_50
paths:
  inference_image_root: ./data/test/DCM
  inference_label_root: ./data/test/outputs_json
  output_dir: ./outputs/
  save_dir: ./outputs/saved_models
  train_image_root: ./data/train/DCM
  train_label_root: ./data/train/outputs_json
random_seed: 42
train:
  batch_size: 4
  criterion:
    name: BCEWithLogitsLoss
  early_stopping:
    evidence: loss
    min_delta: 0.001
    monitor: metric
    patience: 3
  lr_scheduler:
    config:
      factor: 0.1
      min_lr: 1.0e-06
      patience: 20
      verbose: true
    monitor: metric
    name: ReduceLROnPlateau
  metric:
    name: dice_coef
  n_splits: 5
  num_epochs: 100
  optimizer:
    config:
      lr: 0.0001
      momentum: 0.9
      weight_decay: 1.0e-06
    name: Adam
  threshold: 0.5
wandb:
  team_name: dkvltmxhf-hotclip
  user_name: hg
